modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "extendedae_plus_gtladd"
displayURL="https://github.com/GaLicn/ExtendedAE_Plus"
issueTrackerURL = "https://github.com/GaLicn/ExtendedAE_Plus/issues"
version = "${version}"
displayName = "ExtendedAE Plus GTLAdd"
credits = "Savitor (GTL env & minor code)"
authors = "C-H716"
description = "基于主线版本，额外对GT和GTL进行了功能增强。"
logoFile = "extendedae_plus_gtladd.png"

[[dependencies.extendedae_plus_gtladd]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "extendedae_plus_gtladd.mixins.json"
